# Generated by Django 5.1.6 on 2025-03-01 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ContactInfo_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ContactInfo_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ContactInfo',
                'verbose_name_plural': 'CONTACTINFO',
                'ordering': ('-created_by',),
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('objet', models.CharField(max_length=200)),
                ('comments', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ContactMessage_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ContactMessage_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ContactMessage',
                'verbose_name_plural': 'CONTACTMESSAGE',
                'ordering': ('-created_by',),
            },
        ),
    ]
