# Generated by Django 5.1.7 on 2025-05-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("resume", models.TextField()),
                ("contenu", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("date_pub", models.DateTimeField(auto_now_add=True)),
                ("auteur", models.CharField(max_length=100)),
                ("tags", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["-date_pub"],
            },
        ),
    ]
