# Generated by Django 5.1.7 on 2025-05-12 22:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nos_actions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-date_pub"],
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
        migrations.RemoveField(
            model_name="article",
            name="image_url",
        ),
        migrations.AddField(
            model_name="article",
            name="create",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Créé le",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="articles/", verbose_name="Image"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="last_update",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mis à jour par",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="auteur",
            field=models.CharField(max_length=100, verbose_name="Auteur"),
        ),
        migrations.AlterField(
            model_name="article",
            name="contenu",
            field=models.TextField(blank=True, verbose_name="Contenu"),
        ),
        migrations.AlterField(
            model_name="article",
            name="date_pub",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de publication"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="resume",
            field=models.TextField(verbose_name="Résumé"),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.CharField(blank=True, max_length=200, verbose_name="Tags"),
        ),
        migrations.AlterField(
            model_name="article",
            name="titre",
            field=models.CharField(max_length=200, verbose_name="Titre"),
        ),
    ]
