# Generated by Django 5.1.7 on 2025-05-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nos_actions", "0002_alter_article_options_remove_article_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="date_pub",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de publication"
            ),
        ),
    ]
