# Generated by Django 5.1.7 on 2025-05-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nos_actions", "0003_alter_article_date_pub"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_favorite",
            field=models.BooleanField(default=False, verbose_name="Favori"),
        ),
    ]
