# Generated by Django 5.1.6 on 2025-03-01 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_us/')),
                ('area_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AboutUs_createby', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AboutUs_updateby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'A propos',
                'verbose_name_plural': 'A PROPOS',
                'ordering': ('-create_by',),
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priorities', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='missions/')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Missions',
                'verbose_name_plural': 'MISSIONS',
                'ordering': ('-created_by',),
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partenaires/')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Partenaire_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Partenaire_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'PARTENAIRE',
                'ordering': ('-created_by',),
            },
        ),
        migrations.CreateModel(
            name='PlusDeStatistiques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plus_de_statistiques/')),
                ('annee_fondation', models.PositiveIntegerField()),
                ('nombre_donateurs', models.PositiveIntegerField()),
                ('nombre_benevoles', models.PositiveIntegerField()),
                ('activites_reussies', models.PositiveIntegerField()),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PlusDeStatistiques_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PlusDeStatistiques_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlusDeStatistiques',
                'verbose_name_plural': 'PLUSDESTATISTIQUES',
                'ordering': ('-created_by',),
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='volunteers')),
                ('facebook_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Volunteer_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Volunteer_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Volontaires',
                'verbose_name_plural': 'VOLONTAIRES',
                'ordering': ('-created_by',),
            },
        ),
    ]
