# Generated by Django 5.1.7 on 2025-05-12 19:35

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_propos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutus",
            options={
                "ordering": ("-create",),
                "verbose_name": "A propos",
                "verbose_name_plural": "A PROPOS",
            },
        ),
        migrations.AlterModelOptions(
            name="mission",
            options={
                "ordering": ("-create",),
                "verbose_name": "Missions",
                "verbose_name_plural": "MISSIONS",
            },
        ),
        migrations.AlterModelOptions(
            name="partenaire",
            options={
                "ordering": ("-create",),
                "verbose_name": "Partenaire",
                "verbose_name_plural": "PARTENAIRE",
            },
        ),
        migrations.AlterModelOptions(
            name="plusdestatistiques",
            options={
                "ordering": ("-create",),
                "verbose_name": "PlusDeStatistiques",
                "verbose_name_plural": "PLUSDESTATISTIQUES",
            },
        ),
        migrations.AlterModelOptions(
            name="volunteer",
            options={
                "ordering": ("-create",),
                "verbose_name": "Volontaires",
                "verbose_name_plural": "VOLONTAIRES",
            },
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="area_title",
            field=models.CharField(
                help_text="Entrez le titre de la section 'À propos'.", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="create_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="AboutUs_createby",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                help_text="Ajoutez une description détaillée avec du texte, des images, etc."
            ),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="image",
            field=models.ImageField(
                help_text="Ajoutez une image représentative (recommandé : 1920x1080).",
                upload_to="about_us/",
            ),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="update_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="AboutUs_updateby",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mis à jour par",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="missions_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                help_text="Ajoutez une description détaillée de la mission."
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Ajoutez une image pour la mission (optionnel).",
                null=True,
                upload_to="missions/",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="priorities",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                help_text="Listez les priorités de la mission (utilisez des puces si nécessaire)."
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="title",
            field=models.CharField(
                help_text="Entrez le titre de la mission.", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="missions_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mis à jour par",
            ),
        ),
        migrations.AlterField(
            model_name="partenaire",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Partenaire_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="partenaire",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True,
                help_text="Ajoutez une description du partenaire (optionnel).",
            ),
        ),
        migrations.AlterField(
            model_name="partenaire",
            name="image",
            field=models.ImageField(
                help_text="Ajoutez le logo ou une image du partenaire.",
                upload_to="partenaires/",
            ),
        ),
        migrations.AlterField(
            model_name="partenaire",
            name="nom",
            field=models.CharField(
                help_text="Entrez le nom du partenaire.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="partenaire",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Partenaire_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mis à jour par",
            ),
        ),
        migrations.AlterField(
            model_name="plusdestatistiques",
            name="activites_reussies",
            field=models.PositiveIntegerField(
                help_text="Entrez le nombre d'activités réussies."
            ),
        ),
        migrations.AlterField(
            model_name="plusdestatistiques",
            name="annee_fondation",
            field=models.PositiveIntegerField(
                help_text="Entrez l'année de fondation (ex: 2010)."
            ),
        ),
        migrations.AlterField(
            model_name="plusdestatistiques",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="PlusDeStatistiques_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="plusdestatistiques",
            name="image",
            field=models.ImageField(
                help_text="Ajoutez une image pour les statistiques.",
                upload_to="plus_de_statistiques/",
            ),
        ),
        migrations.AlterField(
            model_name="plusdestatistiques",
            name="nombre_benevoles",
            field=models.PositiveIntegerField(
                help_text="Entrez le nombre total de bénévoles."
            ),
        ),
        migrations.AlterField(
            model_name="plusdestatistiques",
            name="nombre_donateurs",
            field=models.PositiveIntegerField(
                help_text="Entrez le nombre total de donateurs."
            ),
        ),
        migrations.AlterField(
            model_name="plusdestatistiques",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="PlusDeStatistiques_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mis à jour par",
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Volunteer_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="facebook_link",
            field=models.URLField(
                blank=True, help_text="Lien vers le profil Facebook (optionnel)."
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="full_name",
            field=models.CharField(
                help_text="Entrez le nom complet du volontaire.", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="image",
            field=models.ImageField(
                help_text="Ajoutez une photo du volontaire.", upload_to="volunteers/"
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="instagram_link",
            field=models.URLField(
                blank=True, help_text="Lien vers le profil Instagram (optionnel)."
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="status",
            field=models.CharField(
                help_text="Entrez le rôle ou statut du volontaire (ex: Membre actif).",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="twitter_link",
            field=models.URLField(
                blank=True, help_text="Lien vers le profil Twitter (optionnel)."
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Volunteer_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mis à jour par",
            ),
        ),
    ]
