# Generated by Django 5.1.7 on 2025-05-12 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_propos", "0002_alter_aboutus_options_alter_mission_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutus",
            options={
                "ordering": ("-create_by",),
                "verbose_name": "A propos",
                "verbose_name_plural": "A PROPOS",
            },
        ),
        migrations.AlterModelOptions(
            name="mission",
            options={
                "ordering": ("-created_by",),
                "verbose_name": "Missions",
                "verbose_name_plural": "MISSIONS",
            },
        ),
        migrations.AlterModelOptions(
            name="partenaire",
            options={
                "ordering": ("-created_by",),
                "verbose_name": "Partenaire",
                "verbose_name_plural": "PARTENAIRE",
            },
        ),
        migrations.AlterModelOptions(
            name="plusdestatistiques",
            options={
                "ordering": ("-created_by",),
                "verbose_name": "PlusDeStatistiques",
                "verbose_name_plural": "PLUSDESTATISTIQUES",
            },
        ),
        migrations.AlterModelOptions(
            name="volunteer",
            options={
                "ordering": ("-created_by",),
                "verbose_name": "Volontaires",
                "verbose_name_plural": "VOLONTAIRES",
            },
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="area_title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="create_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="AboutUs_createby",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="image",
            field=models.ImageField(upload_to="about_us/"),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="update_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="AboutUs_updateby",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="missions_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="mission",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="missions/"),
        ),
        migrations.AlterField(
            model_name="mission",
            name="priorities",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="mission",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="mission",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="missions_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="partenaire",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Partenaire_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="partenaire",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="partenaire",
            name="image",
            field=models.ImageField(upload_to="partenaires/"),
        ),
        migrations.AlterField(
            model_name="partenaire",
            name="nom",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="partenaire",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Partenaire_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="plusdestatistiques",
            name="activites_reussies",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="plusdestatistiques",
            name="annee_fondation",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="plusdestatistiques",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="PlusDeStatistiques_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="plusdestatistiques",
            name="image",
            field=models.ImageField(upload_to="plus_de_statistiques/"),
        ),
        migrations.AlterField(
            model_name="plusdestatistiques",
            name="nombre_benevoles",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="plusdestatistiques",
            name="nombre_donateurs",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="plusdestatistiques",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="PlusDeStatistiques_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Volunteer_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="facebook_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="full_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="image",
            field=models.ImageField(upload_to="volunteers"),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="instagram_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="status",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="twitter_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Volunteer_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
