# Generated by Django 5.1.6 on 2025-03-01 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItemBannier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_url', models.URLField(blank=True)),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CarouselItemBannier_createby', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CarouselItemBannier_updateby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CarouselBannier',
                'verbose_name_plural': 'CAROUSELBANNIER',
                'ordering': ('-create_by',),
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Testimonial_createby', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Testimonial_updateby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Temoignages',
                'verbose_name_plural': 'TEMOIGNAGES',
                'ordering': ('-create_by',),
            },
        ),
    ]
